version: "3"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: url_shortener_db
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    server:
        image: ts-url-shortener-image
        depends_on:
            - db
        ports:
            - "3200:3200"
