version: "3.3"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: url_shortener_db
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    server:
        build: .
        depends_on:
            - db
        ports:
            - "3200:3200"
        environment:
            DB_URL: postgresql://postgres:postgres@db/url_shortener_db
